import {buildingMesh,validateBuildings,footprint} from '../src/buildings';
import {validatePlacements,validateGLB,FurnitureLibrary} from '../src/furniture';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {buildHouse} from '../src/house';
import {PaintController} from '../src/paint';
import {ChairRailController} from '../src/chairRail';
import {CloudDesigns} from '../src/cloudDesigns';
import {captureDesign,applyDesign} from '../src/designDocument';
import {LAND_DEFAULT,updateLand} from '../src/land';
const require=createRequire(import.meta.url);
const {createCanvas,Canvas}=require('@napi-rs/canvas');
globalThis.document={createElement:()=>{const c=createCanvas(256,256);Object.defineProperty(c,'data',{value:undefined});c.toBlob=(cb,type)=>cb(new Blob([c.toBuffer(type||'image/png')],{type}));return c;}};globalThis.HTMLCanvasElement=createCanvas(1,1).constructor;
globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(a=>{this.result=a;this.onloadend?.();});}readAsDataURL(blob){blob.arrayBuffer().then(a=>{this.result='data:'+blob.type+';base64,'+Buffer.from(a).toString('base64');this.onloadend?.();});}};

const values=new Map();const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};globalThis.window={localStorage:storage};
const house=buildHouse();const viewer={house,paint:new PaintController(house.paintRegistry,{storage}),rail:new ChairRailController(house,{storage}),land:{...LAND_DEFAULT},state:{furniture:false},draftStorage:storage,applyVisibility(){},emit(){},setLand(c){this.land={...c};updateLand(this.house,c);this.draftStorage?.setItem('supharat-land-v1',JSON.stringify(c));},toggle(k,v){this.state[k]=v;}};
const id=[...house.paintRegistry.entities.keys()][0];viewer.paint.selected=[id];viewer.paint.setColor('#123456');viewer.paint.apply();
const guest=captureDesign(viewer);let inserted;let release;let asyncOpen=false;let snapshot;let conflict=false;let updated;
const backend={auth:{onAuthStateChange(){return {data:{subscription:{unsubscribe(){}}}}},async getSession(){return {data:{session:null}}},async signOut(){return {error:null}}},from(){let mode;return {update(v){updated=v;mode='update';return this;},insert(v){inserted=v;mode='insert';return this;},select(){return this;},eq(){if(mode!=='update')mode='open';return this;},async single(){if(mode==='update')return conflict?{error:{message:'conflict'}}:{data:{id:inserted.id,name:updated.name,revision:updated.revision,created_at:new Date().toISOString()}};if(mode==='insert')return {data:{id:inserted.id,name:inserted.name,revision:1,created_at:new Date().toISOString()}};if(asyncOpen)return new Promise(r=>{release=r;});return {data:{document:snapshot}};}}}};
let state;const cloud=new CloudDesigns(viewer,s=>{state=s},backend);await new Promise(r=>setTimeout(r,0));
cloud.session({user:{id:'alice',email:'alice@example.test'}});assert.equal(viewer.paint.document().colors[id],undefined);
viewer.paint.selected=[id];viewer.paint.setColor('#aabbcc');viewer.paint.apply();assert.equal(JSON.parse(values.get('supharat-user:alice:supharat-wall-colors-v1')).colors[id],'#aabbcc');assert.equal(JSON.parse(values.get('supharat-wall-colors-v1')).colors[id],'#123456');
await cloud.save('Alice room');assert.equal(inserted.owner_id,undefined);assert.equal(inserted.name,'Alice room');assert.equal(state.items.length,1);snapshot=inserted.document;await cloud.save('Renamed room');assert.equal(updated.revision,2);assert.equal(state.active.revision,2);conflict=true;await cloud.save('Conflict');assert.ok(state.error);assert.equal(state.active.revision,2);conflict=false;
const before=captureDesign(viewer);assert.throws(()=>applyDesign(viewer,{...snapshot,moulding:{bad:true}}));assert.deepEqual(captureDesign(viewer),before);
await cloud.signOut();assert.deepEqual(viewer.paint.document(),guest.paint);
cloud.session({user:{id:'bob',email:'bob@example.test'}});assert.equal(viewer.paint.document().colors[id],undefined);assert.equal(state.items.length,0);
cloud.session({user:{id:'alice',email:'alice@example.test'}});assert.equal(viewer.paint.document().colors[id],'#aabbcc');
viewer.paint.setColor('#445566');viewer.paint.apply();await cloud.open('saved');assert.equal(viewer.paint.document().colors[id],'#aabbcc');cloud.restore();assert.equal(viewer.paint.document().colors[id],'#445566');
asyncOpen=true;const pending=cloud.open('saved');await new Promise(r=>setTimeout(r,0));cloud.session({user:{id:'bob',email:'bob@example.test'}});release({data:{document:snapshot}});await pending;assert.equal(viewer.paint.document().colors[id],undefined);assert.equal(state.user.id,'bob');assert.equal(cloud.previous,null);
cloud.duplicate(true);assert.deepEqual(viewer.paint.document().colors,{});
viewer.paint.selected=[id];viewer.paint.setColor('#abcdef');viewer.paint.apply();
viewer.toggle('furniture',true);assert.equal(cloud.history.cursor,2);
viewer.paint.undo();assert.equal(viewer.state.furniture,false);assert.equal(viewer.paint.document().colors[id],'#abcdef');
viewer.rail.undo();assert.equal(viewer.paint.document().colors[id],undefined);
viewer.paint.redo();assert.equal(viewer.paint.document().colors[id],'#abcdef');
const history=cloud.history.document(),saved=captureDesign(viewer);
cloud.history.load(saved,history);viewer.rail.redo();assert.equal(viewer.state.furniture,true);
cloud.history.go(0);viewer.paint.setColor('#112233');viewer.paint.apply();assert.equal(cloud.history.entries.length,2);assert.equal(cloud.history.cursor,1);
const safe=captureDesign(viewer);assert.throws(()=>cloud.history.load(saved,{...history,cursor:999}));assert.deepEqual(captureDesign(viewer),safe);
for(let n=0;n<60;n++)viewer.toggle('furniture',n%2===0);assert.equal(cloud.history.entries.length,51);
cloud.duplicate(true);assert.deepEqual(viewer.paint.document().colors,{});assert.equal(viewer.state.furniture,false);assert.equal(state.active,null);
console.log('PASS: unified undo/redo, restored redo stack, branching, bounded history, invalid history atomicity, immutable baseline duplication');
const placement={id:crypto.randomUUID(),assetId:'builtin-chair',name:'Chair',floor:0,x:5,z:6,rotation:0,scale:1};
viewer.furnitureScene.set([placement]);cloud.history.record('Added chair');await new Promise(r=>setTimeout(r,0));assert.equal(viewer.furnitureScene.group.children.length,1);
const furnitureSaved=captureDesign(viewer),furnitureHistory=cloud.history.document();cloud.history.go(cloud.history.cursor-1);assert.equal(viewer.furnitureScene.items.length,0);cloud.history.load(furnitureSaved,furnitureHistory);assert.deepEqual(viewer.furnitureScene.document(),[placement]);
assert.throws(()=>validatePlacements([placement,{...placement}]));assert.throws(()=>validatePlacements([{...placement,scale:Infinity}]));
const model=await cloud.library.model('builtin-chair');const glb=await new GLTFExporter().parseAsync(model,{binary:true});validateGLB(glb);assert.throws(()=>validateGLB(new ArrayBuffer(20)));
let uploaded=false,published=false;const uploadBackend={storage:{from(){return {async upload(path,blob){uploaded=path.endsWith('.glb')&&blob.size>0;return {};}}}},from(){return {async insert(row){published=row.category==='Seating'&&row.width>0;return {};},select(){return this;},order(){return this;},async limit(){return {data:[]};}}}};
const library=new FurnitureLibrary(uploadBackend);await library.upload({arrayBuffer:async()=>glb},'Test chair','Seating');assert.ok(uploaded&&published);
cloud.session({user:{id:'alice'}});assert.equal(viewer.furnitureScene.items.length,0);
console.log('PASS: furniture geometry, placement roundtrip, undo/redo, account isolation, GLB parsing, catalog upload pipeline and invalid placement rejection');
const shell={id:'shell',name:'Guesthouse',points:footprint('l',4,5),x:0,z:12,height:3,floors:2,rotation:45,roof:'flat',color:'#ffffff'};
validateBuildings([shell]);const shellMesh=buildingMesh(shell);assert.equal(shellMesh.children.length,15);
assert.throws(()=>validateBuildings([{...shell,points:[[0,0],[4,4],[0,4],[4,0]]}]));assert.throws(()=>validateBuildings([{...shell,height:NaN}]));
viewer.buildings.set([shell]);cloud.history.record('Building');const shellDoc=captureDesign(viewer),shellHistory=cloud.history.document();cloud.history.go(cloud.history.cursor-1);assert.equal(viewer.buildings.items.length,0);cloud.history.load(shellDoc,shellHistory);assert.deepEqual(viewer.buildings.document(),[shell]);cloud.duplicate(true);assert.equal(viewer.buildings.items.length,0);
console.log('PASS: building geometry, invalid polygon rejection, saved shell history, undo and baseline isolation');
cloud.dispose();console.log('PASS: guest/account draft isolation, cloud snapshot save/open/restore, invalid-load atomicity, stale account response discarded');
