import {BuildingScene} from './buildings';
import {FurnitureLibrary,FurnitureScene} from './furniture';
import {DesignHistory,baselineDesign} from './designHistory';
import {createClient} from '@supabase/supabase-js';
import {captureDesign,applyDesign,switchDraftWorkspace} from './designDocument';
const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
let client=null;
// Publishable keys only: never allow a server secret to be bundled as configuration.
if(url&&key?.startsWith('sb_publishable_')&&!url.includes('YOUR_PROJECT')){
 try{if(new URL(url).protocol==='https:')client=createClient(url,key,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});}catch{}
}
export class CloudDesigns {
 constructor(viewer,onChange,backend=client){this.viewer=viewer;this.onChange=onChange;this.client=backend;this.generation=0;this.previous=null;this.disposed=false;this.state={configured:!!backend,loading:!!backend,user:null,items:[],busy:false,error:'',message:'',more:false};viewer.buildings=new BuildingScene(viewer);this.library=new FurnitureLibrary(backend);viewer.furnitureScene=new FurnitureScene(viewer,this.library);const visibility=viewer.applyVisibility.bind(viewer);viewer.applyVisibility=()=>{visibility();viewer.furnitureScene.visibility();viewer.buildings.visibility();};this.history=new DesignHistory(viewer,()=>{this.state.dirty=true;this.emit();});this.emit();if(!backend)return;
 this.subscription=backend.auth.onAuthStateChange((_event,session)=>this.session(session)).data.subscription;
 const initialGeneration=this.generation;backend.auth.getSession().then(({data,error})=>{if(this.disposed||this.generation!==initialGeneration)return;if(error)this.patch({loading:false,error:'Sign-in could not be restored. Please try Google sign-in again.'});else this.session(data.session);}).catch(()=>{if(!this.disposed&&this.generation===initialGeneration)this.patch({loading:false,error:'Cannot connect to sign-in. Check your connection.'});});
 }
 emit(){if(!this.disposed)this.onChange({...this.state,history:this.history?.document()});}
 patch(next){Object.assign(this.state,next);this.emit();}
 session(session){if(this.disposed)return;const user=session?.user||null;if(user?.id!==this.state.user?.id){this.generation++;this.previous=null;switchDraftWorkspace(this.viewer,user?.id||null);this.viewer.furnitureScene.set([]);this.viewer.buildings.set([]);this.history.reset(captureDesign(this.viewer));this.state.active=null;this.state.dirty=false;this.patch({user,items:[],busy:false,more:false,error:'',message:'',loading:false});}else this.patch({user,loading:false});}
 async signIn(){if(!this.client||this.state.busy)return;this.patch({busy:true,error:''});try{const {error}=await this.client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname,queryParams:{prompt:'select_account'}}});if(error)throw error;}catch{this.patch({error:'Google sign-in could not start. Please try again.'});}finally{this.patch({busy:false});}}
 async updateProfile(name){return this.run(async current=>{name=name.trim();if(!name||name.length>80)throw new Error('Enter a display name of 1–80 characters.');const {data,error}=await this.client.auth.updateUser({data:{display_name:name}});if(!current())return;if(error)throw new Error('Profile could not be saved. Please try again.');this.patch({user:data.user,message:'Profile saved.'});});}
 async signOut(scope='local'){if(!this.client||this.state.busy)return;this.patch({busy:true,error:''});try{const {error}=await this.client.auth.signOut({scope});if(error)throw error;this.session(null);}catch{this.patch({error:'Sign-out failed. Please try again.'});}finally{this.patch({busy:false});}}
 async run(action){if(!this.state.user||this.state.busy)return;const generation=this.generation;this.patch({busy:true,error:'',message:''});try{await action(()=>!this.disposed&&generation===this.generation);}catch(e){if(generation===this.generation)this.patch({error:e.message||'Could not connect. Your browser draft is unchanged.'});}finally{if(generation===this.generation)this.patch({busy:false});}}
 async list(more=false){return this.run(async current=>{const start=more?this.state.items.length:0;const {data,error}=await this.client.from('interior_designs').select('id,name,created_at').order('created_at',{ascending:false}).order('id',{ascending:false}).range(start,start+49);if(!current())return;if(error)throw new Error('Could not load your designs. Check your connection or project setup.');this.patch({items:more?[...this.state.items,...data]:data,more:data.length===50});});}
 async save(name){return this.run(async current=>{name=name.trim();if(!name||name.length>80)throw new Error('Give your design a name of 1–80 characters.');const document=captureDesign(this.viewer),history=this.history.document(),active=this.state.active;const payload={name,document,history};let query=this.client.from('interior_designs');query=active?query.update({...payload,revision:active.revision+1}).eq('id',active.id).eq('revision',active.revision):query.insert({id:crypto.randomUUID(),...payload});const {data,error}=await query.select('id,name,created_at,revision').single();if(!current())return;if(error)throw new Error('Save was not confirmed. Another device may have saved a newer version. Your current edits remain here; duplicate them before reopening the saved copy.');this.patch({active:data,dirty:JSON.stringify(history)!==JSON.stringify(this.history.document()),items:[data,...this.state.items.filter(d=>d.id!==data.id)],message:'Private copy and edit history saved.'});});}
 duplicate(baseline=false){if(this.state.busy)return;this.previous={document:captureDesign(this.viewer),history:this.history.document(),active:this.state.active};if(baseline)this.history.load(baselineDesign());else this.history.reset(captureDesign(this.viewer),'Duplicated design');this.patch({active:null,dirty:true,message:baseline?'New copy of the original house. Name it and save to your account.':'New independent copy. Name it and save to your account.'});}
 async open(id){return this.run(async current=>{const {data,error}=await this.client.from('interior_designs').select('id,name,created_at,revision,document,history').eq('id',id).single();if(!current())return;if(error)throw new Error('This design is unavailable or belongs to another account.');const before={document:captureDesign(this.viewer),history:this.history.document(),active:this.state.active};this.history.load(data.document,data.history);this.previous=before;this.patch({active:{id:data.id,name:data.name,created_at:data.created_at,revision:data.revision},dirty:false,message:'Private copy opened with its saved edit history.'});});}
 restore(){if(!this.previous||this.state.busy)return;try{const previous=this.previous;this.history.load(previous.document,previous.history);this.previous=null;this.patch({active:previous.active,dirty:true,message:'Previous draft restored.',error:''});}catch(e){this.patch({error:e.message});}}
 dispose(){this.viewer.buildings.destroy();this.viewer.furnitureScene.destroy();this.disposed=true;this.generation++;this.subscription?.unsubscribe();}
}
