import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
export const STARTER_ASSETS=[{id:'builtin-chair',name:'Dining chair',category:'Seating',width:.5,height:.85,depth:.55},{id:'builtin-sofa',name:'Two-seat sofa',category:'Seating',width:1.8,height:.85,depth:.85},{id:'builtin-table',name:'Dining table',category:'Tables',width:1.6,height:.75,depth:.85},{id:'builtin-bed',name:'Double bed',category:'Beds',width:1.6,height:.65,depth:2}];
export function validatePlacements(items=[]){if(!Array.isArray(items)||items.length>100)throw new Error('A design supports up to 100 furniture items.');const ids=new Set();for(const p of items){if(!p||typeof p.id!=='string'||ids.has(p.id)||!/^builtin-(chair|sofa|table|bed)$|^[0-9a-f-]{36}$/.test(p.assetId)||typeof p.name!=='string'||p.name.length>80||![0,1].includes(p.floor)||!['x','z','rotation','scale'].every(k=>Number.isFinite(p[k]))||Math.abs(p.x)>100||Math.abs(p.z)>100||Math.abs(p.rotation)>360||p.scale<.1||p.scale>5)throw new Error('Invalid furniture placement.');ids.add(p.id);}}
export function validateGLB(buffer){if(buffer.byteLength>10*1024*1024||buffer.byteLength<20)throw new Error('Choose a self-contained GLB under 10 MB.');const v=new DataView(buffer);if(v.getUint32(0,true)!==0x46546c67||v.getUint32(4,true)!==2||v.getUint32(8,true)!==buffer.byteLength||v.getUint32(16,true)!==0x4e4f534a)throw new Error('Choose a valid GLB 2.0 file.');const len=v.getUint32(12,true);if(len>buffer.byteLength-20)throw new Error('Invalid GLB JSON chunk.');const json=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,20,len)));if([...(json.buffers||[]),...(json.images||[])].some(r=>r.uri&&!r.uri.startsWith('data:')))throw new Error('Embed all textures and buffers in the GLB. External files are not supported.');return json;}
function dispose(root){root.traverse(o=>{o.geometry?.dispose();for(const m of o.material?Array.isArray(o.material)?o.material:[o.material]:[]){for(const t of Object.values(m))if(t?.isTexture)t.dispose();m.dispose();}});}
function starter(asset){const g=new T.Group(),material=new T.MeshStandardMaterial({color:asset.category==='Seating'?'#aaa18c':'#b78e66'});const box=(w,h,d,x,y,z)=>{const m=new T.Mesh(new T.BoxGeometry(w,h,d),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);};const {width:w,height:h,depth:d}=asset;if(asset.id==='builtin-bed'){box(w,.3,d,0,.2,0);box(w,.15,d*.85,0,.425,.1);box(w,h,.1,0,h/2,-d/2);}else if(asset.id==='builtin-sofa'){box(w,.4,d,0,.3,0);box(w,h,.15,0,h/2,-d/2+.075);for(const x of [-w/2+.08,w/2-.08])box(.16,.6,d,x,.3,0);}else{const seat=asset.id==='builtin-chair'?.45:h;box(w,.08,d,0,seat-.04,0);for(const x of [-w/2+.07,w/2-.07])for(const z of [-d/2+.07,d/2-.07])box(.06,seat-.08,.06,x,(seat-.08)/2,z);if(asset.id==='builtin-chair')box(w,h-.45,.06,0,(h+.45)/2,-d/2+.03);}return g;}
export class FurnitureLibrary{
 constructor(client){this.client=client;this.assets=[...STARTER_ASSETS];}
 async list(){if(!this.client)return this.assets;const {data,error}=await this.client.from('furniture_assets').select('*').order('name').limit(500);if(error)throw new Error('Shared library unavailable. Check sign-in and furniture setup.');this.assets=[...STARTER_ASSETS,...data];return this.assets;}
 async model(id){const builtin=STARTER_ASSETS.find(a=>a.id===id);if(builtin)return starter(builtin);if(!this.client)throw new Error('Sign in to load uploaded furniture.');const {data,error}=await this.client.storage.from('furniture-assets').download(`${id}.glb`);if(error)throw new Error('Furniture asset unavailable.');const buffer=await data.arrayBuffer();validateGLB(buffer);const gltf=await new GLTFLoader().parseAsync(buffer,'');const root=gltf.scene;const bounds=new T.Box3().setFromObject(root),center=bounds.getCenter(new T.Vector3());root.position.x-=center.x;root.position.z-=center.z;root.position.y-=bounds.min.y;const wrapper=new T.Group();wrapper.add(root);return wrapper;}
 async upload(file,name,category){name=name.trim();if(!name||name.length>80)throw new Error('Enter an asset name (1–80 characters).');if(!file)throw new Error('Choose a GLB file.');if(file.size>10*1024*1024)throw new Error('Choose a GLB under 10 MB.');if(!this.client)throw new Error('Connect Google/Supabase to upload shared assets.');const buffer=await file.arrayBuffer();validateGLB(buffer);const parsed=await new GLTFLoader().parseAsync(buffer,'');const bounds=new T.Box3().setFromObject(parsed.scene),size=bounds.getSize(new T.Vector3());dispose(parsed.scene);if(![size.x,size.y,size.z].every(n=>Number.isFinite(n)&&n>.001&&n<=30))throw new Error('Use metres, with dimensions between 1 mm and 30 m.');const id=crypto.randomUUID(),path=`${id}.glb`;const {error}=await this.client.storage.from('furniture-assets').upload(path,new Blob([buffer],{type:'model/gltf-binary'}),{contentType:'model/gltf-binary',upsert:false});if(error)throw new Error('Upload failed. Only library managers can add shared assets.');const result=await this.client.from('furniture_assets').insert({id,name,category,width:size.x,height:size.y,depth:size.z});if(result.error){await this.client.storage.from('furniture-assets').remove([path]);throw new Error('Could not publish this asset. Please retry.');}return this.list();}
}
export class FurnitureScene{
 constructor(viewer,library){this.viewer=viewer;this.library=library;this.items=[];this.generation=0;this.group=new T.Group();this.group.name='User furniture';viewer.house.root.add(this.group);this.errors=[];}
 document(){return structuredClone(this.items);}
 set(items){validatePlacements(items);this.items=structuredClone(items);this.pending=this.rebuild();}
 async rebuild(){const generation=++this.generation;for(const child of [...this.group.children]){this.group.remove(child);dispose(child);}this.errors=[];await Promise.all(this.items.map(async item=>{try{const model=await this.library.model(item.assetId);if(generation!==this.generation){dispose(model);return;}model.name=item.name;model.position.set(item.x,item.floor?4:.6,item.z);model.rotation.y=item.rotation*Math.PI/180;model.scale.setScalar(item.scale);model.userData.floor=item.floor;this.group.add(model);this.visibility();}catch(e){if(generation===this.generation)this.errors.push(`${item.name}: ${e.message}`);}}));this.onChange?.();}
 visibility(){for(const o of this.group.children)o.visible=this.viewer.state.mode!==(o.userData.floor?'ground':'upper');}
 destroy(){this.generation++;for(const child of this.group.children)dispose(child);this.group.removeFromParent();}
}
