import * as T from 'three';
export const mat=(color,roughness=.75,extra={})=>new T.MeshStandardMaterial({color,roughness,...extra});
export function box(g,name,x,y,z,w,h,d,m){const o=new T.Mesh(new T.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.name=name;o.castShadow=true;o.receiveShadow=true;g.add(o);return o;}
export function cylinder(g,name,x,y,z,r,h,m,r2=r){const o=new T.Mesh(new T.CylinderGeometry(r2,r,h,20),m);o.position.set(x,y,z);o.name=name;o.castShadow=true;o.receiveShadow=true;g.add(o);return o;}
export function sphere(g,name,x,y,z,sx,sy,sz,m){const o=new T.Mesh(new T.SphereGeometry(1,20,12),m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.name=name;o.castShadow=true;g.add(o);return o;}
export function beam(g,name,a,b,r,m){let va=new T.Vector3(...a),vb=new T.Vector3(...b);const o=cylinder(g,name,...va.clone().add(vb).multiplyScalar(.5).toArray(),r,va.distanceTo(vb),m);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),vb.sub(va).normalize());return o;}
export function polygon(g,name,points,y,thickness,m){const s=new T.Shape();points.forEach(([x,z],i)=>i?s.lineTo(x,-z):s.moveTo(x,-z));s.closePath();const geo=new T.ExtrudeGeometry(s,{depth:thickness,bevelEnabled:false});geo.rotateX(-Math.PI/2);const o=new T.Mesh(geo,m);o.position.y=y-thickness;o.name=name;o.castShadow=true;o.receiveShadow=true;g.add(o);return o;}
export function surface(g,name,vertices,m){const geo=new T.BufferGeometry();const pos=[],uv=[];for(let i=1;i<vertices.length-1;i++){for(const p of [vertices[0],vertices[i],vertices[i+1]]){pos.push(...p);uv.push(p[0]*2.7,p[2]*2.7);}}geo.setAttribute('position',new T.Float32BufferAttribute(pos,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.computeVertexNormals();const mesh=new T.Mesh(geo,m);mesh.name=name;mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
export function texture(kind){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');
 if(kind==='wood'){ctx.fillStyle='#b89670';ctx.fillRect(0,0,256,256);for(let i=0;i<160;i++){ctx.strokeStyle=`rgba(65,39,21,${.02+(i%7)*.011})`;ctx.beginPath();ctx.moveTo(i*1.7,0);ctx.bezierCurveTo(i*1.7+5,60,i*1.7-5,190,i*1.7,256);ctx.stroke();}}
 if(kind==='tile'){ctx.fillStyle='#e8e5de';ctx.fillRect(0,0,256,256);ctx.strokeStyle='#cecdc6';ctx.lineWidth=1.2;ctx.strokeRect(0,0,256,256);for(let i=0;i<1000;i++){ctx.fillStyle=`rgba(130,125,115,${(i%5)*.012})`;ctx.fillRect((i*73)%256,(i*131)%256,2,1);}}
 if(kind==='roof'){ctx.fillStyle='#444a4c';ctx.fillRect(0,0,256,256);for(let y=0;y<256;y+=64)for(let x=0;x<256;x+=32){let gr=ctx.createLinearGradient(x,0,x+32,0);gr.addColorStop(0,'#454b4d');gr.addColorStop(.4,'#586064');gr.addColorStop(1,'#30383b');ctx.fillStyle=gr;ctx.fillRect(x,y,31,62);ctx.fillStyle='#6a7172';ctx.fillRect(x,y+60,31,2);}}
 if(kind==='stone'){ctx.fillStyle='#8b8680';ctx.fillRect(0,0,256,256);for(let y=0;y<256;y+=16)for(let x=-32;x<256;x+=64){const xx=x+(y%32?32:0);ctx.fillStyle=['#8b8680','#99938a','#aaa399','#76756f'][(x/64+y/16+20)%4|0];ctx.fillRect(xx+1,y+1,62,14);}}
 const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=4;return t;}
