import * as T from 'three';
import {roomAt,roomLabel,PAINT_ROOMS} from './paintRooms';
export const STORAGE_KEY='supharat-wall-colors-v1';
export const validColor=c=>typeof c==='string'&&/^#[0-9a-f]{6}$/i.test(c);
export class PaintRegistry {
 constructor(){this.entities=new Map();this.meshes=[];}
 face(mesh,slot,{id,floor,room,label},base){let entity=this.entities.get(id);if(!entity){const material=base.clone();material.name=`Wall paint · ${label}`;material.userData={paintId:id,room,floor};entity={id,floor,room,label,material,original:'#'+base.color.getHexString(),faces:[]};this.entities.set(id,entity);}mesh.material[slot]=entity.material;mesh.userData.paintFaces??={};mesh.userData.paintFaces[slot]=id;entity.faces.push({mesh,slot});}
 wall(mesh,{key,floor,axis,fixed,middle,thickness},base){mesh.material=Array(6).fill(base);this.meshes.push(mesh);for(const sign of[1,-1]){const room=roomAt(floor,axis==='x'?middle:fixed+sign*(thickness/2+.035),axis==='x'?fixed+sign*(thickness/2+.035):middle);const ext=room.startsWith('exterior');const direction=axis==='x'?(sign>0?(ext?'Front exterior':'Rear wall'):(ext?'Rear exterior':'Front wall')):(sign>0?(ext?'Right exterior':'Left wall'):(ext?'Left exterior':'Right wall'));const slot=axis==='x'?(sign>0?4:5):(sign>0?0:1);this.face(mesh,slot,{id:`${key}:${sign}:${room}`,floor,room,label:`${roomLabel(room)} · ${direction}`},base);}}
 curved(mesh,floor,base){mesh.material=Array(6).fill(base);this.meshes.push(mesh);for(const slot of[4,5]){const room=slot===5?`stair${floor}`:`exterior${floor}`;this.face(mesh,slot,{id:`curve:${floor}:${slot}`,floor,room,label:slot===5?'Stair hall · Curved wall':'Exterior · Curved stair wall'},base);}}
}
export class PaintController {
 constructor(registry,{storage=null,onChange=()=>{}}={}){this.registry=registry;this.storage=storage;this.onChange=onChange;this.enabled=false;this.scope='wall';this.selected=[];this.room='living';this.floor=0;this.color='#c5cdb9';this.past=[];this.future=[];this.message='Click a plaster wall to select it.';this.saved=false;try{const saved=storage?.getItem(STORAGE_KEY);if(saved){const doc=JSON.parse(saved);if(doc.version===1&&doc.colors&&typeof doc.colors==='object'){for(const[id,color]of Object.entries(doc.colors)){const e=registry.entities.get(id);if(e&&validColor(color))e.material.color.set(color);}}}this.saved=!!storage;}catch{this.saved=false;}}
 targets(){const all=[...this.registry.entities.values()];if(this.scope==='house')return all;if(this.scope==='floor')return all.filter(e=>e.floor===this.floor);if(this.scope==='room')return all.filter(e=>e.room===this.room);return this.selected.map(id=>this.registry.entities.get(id)).filter(Boolean).slice(this.scope==='wall'?-1:0);}
 snapshot(){const targets=this.targets(),colors=[...new Set(targets.map(e=>'#'+e.material.color.getHexString()))];return {enabled:this.enabled,scope:this.scope,selected:this.selected.map(id=>{const e=this.registry.entities.get(id);return {id,label:e.label,floor:e.floor};}),room:this.room,floor:this.floor,color:this.color,count:targets.length,current:colors.length===1?colors[0]:colors.length?'Mixed colors':null,canUndo:!!this.past.length,canRedo:!!this.future.length,message:this.message,saved:this.saved,painted:[...this.registry.entities.values()].filter(e=>'#'+e.material.color.getHexString()!==e.original).length};}
 emit(){this.onChange(this.snapshot());}
 setEnabled(v){this.enabled=v;this.emit();}
 setScope(scope){if(!['wall','walls','room','floor','house'].includes(scope))return;this.scope=scope;if(scope==='wall')this.selected=this.selected.slice(-1);this.message=scope==='walls'?'Click walls to add or remove them.':scope==='wall'?'Click a plaster wall to select it.':'Choose a color, then apply it to the target below.';this.emit();}
 select(id,add=false){const e=this.registry.entities.get(id);if(!e)return;if(add&&this.scope==='wall')this.scope='walls';if(this.scope==='walls'){this.selected=this.selected.includes(id)?this.selected.filter(x=>x!==id):[...this.selected,id];}else this.selected=[id];this.floor=e.floor;if(!e.room.startsWith('exterior'))this.room=e.room;else if(this.scope==='room'){this.room='';this.message='This is an exterior face. Choose an interior room in the panel.';this.emit();return;}this.message=this.scope==='walls'?`${this.selected.length} wall ${this.selected.length===1?'face':'faces'} selected.`:e.label;this.emit();}
 remove(id){this.selected=this.selected.filter(x=>x!==id);this.emit();}
 clear(){this.selected=[];this.message='Selection cleared.';this.emit();}
 setRoom(id){const r=PAINT_ROOMS.find(r=>r.id===id);if(r){this.room=id;this.floor=r.floor;this.emit();}}
 setFloor(f){this.floor=Number(f)===1?1:0;this.emit();}
 setColor(c){if(validColor(c)){this.color=c.toLowerCase();this.emit();}}
 commit(changes,label){const actual=changes.filter(c=>c.before!==c.after);if(!actual.length){this.message='These wall faces already have that color.';this.emit();return false;}for(const c of actual)this.registry.entities.get(c.id).material.color.set(c.after);this.past.push(actual);if(this.past.length>50)this.past.shift();this.future=[];this.message=label;this.persist();this.emit();return true;}
 apply(){if(!validColor(this.color))return false;return this.commit(this.targets().map(e=>({id:e.id,before:'#'+e.material.color.getHexString(),after:this.color})),`Applied ${this.color.toUpperCase()} to ${this.targets().length} wall ${this.targets().length===1?'face':'faces'}.`);}
 reset(){return this.commit(this.targets().map(e=>({id:e.id,before:'#'+e.material.color.getHexString(),after:e.original})),'Original wall color restored for this target.');}
 undo(){const action=this.past.pop();if(!action)return;for(const c of action)this.registry.entities.get(c.id).material.color.set(c.before);this.future.push(action);this.message='Undid the last color change.';this.persist();this.emit();}
 redo(){const action=this.future.pop();if(!action)return;for(const c of action)this.registry.entities.get(c.id).material.color.set(c.after);this.past.push(action);this.message='Redid the color change.';this.persist();this.emit();}
 document(){return {format:'supharat-wall-colors',version:1,colors:Object.fromEntries([...this.registry.entities.values()].filter(e=>'#'+e.material.color.getHexString()!==e.original).map(e=>[e.id,'#'+e.material.color.getHexString()]))};}
 persist(){try{if(!this.storage)throw new Error();this.storage.setItem(STORAGE_KEY,JSON.stringify(this.document()));this.saved=true;}catch{this.saved=false;}}
 importDocument(doc){if(!doc||doc.format!=='supharat-wall-colors'||doc.version!==1||!doc.colors||Array.isArray(doc.colors)||typeof doc.colors!=='object')throw new Error('Choose a Supharat wall-colors JSON file.');for(const[id,color]of Object.entries(doc.colors)){if(!this.registry.entities.has(id)||!validColor(color))throw new Error('This color file does not match the house model.');}return this.commit([...this.registry.entities.values()].map(e=>({id:e.id,before:'#'+e.material.color.getHexString(),after:doc.colors[e.id]||e.original})),'Loaded saved wall colors.');}
}
// Face outlines are separate from the model, so they never appear in a GLB export.
export function makePaintOutlines(registry,ids){const group=new T.Group();group.name='Paint selection';const lineMat=new T.LineBasicMaterial({color:'#3e96ae',transparent:true,opacity:.95,depthTest:true});for(const id of ids){const entity=registry.entities.get(id);for(const {mesh,slot}of entity?.faces||[]){const p=mesh.geometry.attributes.position,n=mesh.geometry.attributes.normal;const points=[0,1,3,2,0].map(i=>new T.Vector3().fromBufferAttribute(p,slot*4+i).addScaledVector(new T.Vector3().fromBufferAttribute(n,slot*4+i),.009));const line=new T.Line(new T.BufferGeometry().setFromPoints(points),lineMat);line.matrixAutoUpdate=false;line.matrix.copy(mesh.matrixWorld);line.userData.owner=mesh;group.add(line);}}return group;}
