import * as T from 'three';
export const PANEL_DEFAULT={layout:'panels',panelWidth:.9,gap:.18,frameWidth:.045,doubleFrame:true};
export function validPanels(c){return (c.layout===undefined||['panels','full','lower','rail'].includes(c.layout))&&(!c.layout||c.layout==='rail'||(Number.isFinite(c.panelWidth)&&c.panelWidth>=.5&&c.panelWidth<=1.5&&Number.isFinite(c.gap)&&c.gap>=.1&&c.gap<=.35&&Number.isFinite(c.frameWidth)&&c.frameWidth>=.025&&c.frameWidth<=.07&&typeof c.doubleFrame==='boolean'));}
const union=spans=>{const out=[];for(const [a,b]of spans.sort((a,b)=>a[0]-b[0])){const last=out.at(-1);if(last&&a<=last[1]+.002)last[1]=Math.max(last[1],b);else out.push([a,b]);}return out;};
const intersect=(a,b)=>union(a.flatMap(([l,r])=>b.map(([x,y])=>[Math.max(l,x),Math.min(r,y)]).filter(([x,y])=>y-x>.001)));
export function panelRectangles(entity,config){if(!['panels','full','lower'].includes(config.layout))return[];const groups=new Map(),up=new T.Vector3(0,1,0),base=entity.floor?4:.6;
 for(const {mesh,slot}of entity.faces){mesh.updateWorldMatrix(true,false);const p=mesh.geometry.attributes.position,n=new T.Vector3().fromBufferAttribute(mesh.geometry.attributes.normal,slot*4).transformDirection(mesh.matrixWorld);const u=new T.Vector3().crossVectors(up,n).normalize(),pts=[0,1,2,3].map(i=>new T.Vector3().fromBufferAttribute(p,slot*4+i).applyMatrix4(mesh.matrixWorld)),plane=pts[0].dot(n);const key=[...n.toArray(),plane].map(v=>v.toFixed(4)).join(':');let g=groups.get(key);if(!g){g={n,u,plane,rects:[],openings:mesh.userData.railOpenings};groups.set(key,g);}const ys=pts.map(p=>p.y).sort((a,b)=>a-b);g.rects.push({a:Math.min(...pts.map(p=>p.dot(u))),b:Math.max(...pts.map(p=>p.dot(u))),lo:Math.max(ys[0],ys[1]),hi:Math.min(ys[2],ys[3])});}
 const result=[];for(const g of groups.values()){const top=Math.min(base+(entity.floor?3.2:3.15),Math.max(...g.rects.map(r=>r.hi)));const lower=['lower',base+.24,base+config.height-config.size/2-.12],upper=['upper',base+config.height+config.size/2+.12,top-.18];const bands=config.layout==='full'?[['full',base+.24,top-.18]]:config.layout==='lower'?[lower]:[lower,upper];
 for(const [zone,lo,hi]of bands){if(hi-lo<.32)continue;const breaks=[lo,hi,...g.rects.flatMap(r=>[r.lo,r.hi]).filter(y=>y>lo&&y<hi)].sort((a,b)=>a-b);let spans=[[-Infinity,Infinity]];for(let i=0;i<breaks.length-1;i++){const y=(breaks[i]+breaks[i+1])/2;spans=intersect(spans,union(g.rects.filter(r=>r.lo<=y+.001&&r.hi>=y-.001).map(r=>[r.a,r.b])));}
 for(const op of g.openings?.openings||[]){const margin=op.type==='window'?.16:.05;if(hi<base+(op.s||0)-margin||lo>base+(op.s||0)+op.h+margin)continue;const v=g.openings.axis==='x'?g.u.x:g.u.z,offset=(g.openings.axis==='x'?g.u.z:g.u.x)*g.openings.fixed;const [l,r]=[(op.c-op.w/2-margin)*v+offset,(op.c+op.w/2+margin)*v+offset].sort((a,b)=>a-b);spans=spans.flatMap(([a,b])=>b<=l||a>=r?[[a,b]]:[[a,Math.min(b,l)],[Math.max(a,r),b]].filter(([a,b])=>b>a));}
 for(const [a,b]of spans){const left=a+config.gap/2,right=b-config.gap/2,width=right-left;if(width<.35)continue;const count=Math.max(1,Math.round((width+config.gap)/(config.panelWidth+config.gap)));const w=(width-(count-1)*config.gap)/count;if(w<.35)continue;for(let i=0;i<count;i++)result.push({a:left+i*(w+config.gap),b:left+i*(w+config.gap)+w,lo,hi,zone,n:g.n,u:g.u,plane:g.plane});}
 }}return result;}
function ringGeometry(w,h,band,depth,rounded=false){const shape=new T.Shape();shape.moveTo(-w/2,-h/2);shape.lineTo(w/2,-h/2);shape.lineTo(w/2,h/2);shape.lineTo(-w/2,h/2);shape.closePath();const hole=new T.Path();hole.moveTo(-w/2+band,-h/2+band);hole.lineTo(-w/2+band,h/2-band);hole.lineTo(w/2-band,h/2-band);hole.lineTo(w/2-band,-h/2+band);hole.closePath();shape.holes.push(hole);return new T.ExtrudeGeometry(shape,{depth,bevelEnabled:true,bevelSegments:rounded?5:1,steps:1,bevelSize:rounded?Math.min(band*.2,.006):.002,bevelThickness:rounded?Math.min(depth*.25,.005):.002});}
export function addPanelFrames(parent,entity,config,material){const up=new T.Vector3(0,1,0);for(const r of panelRectangles(entity,config)){const panel=new T.Group();panel.name='Wall panel frame · '+r.zone;panel.userData={panelZone:r.zone,wallId:entity.id};panel.position.copy(r.u).multiplyScalar((r.a+r.b)/2).addScaledVector(r.n,r.plane+.004);panel.position.y=(r.lo+r.hi)/2;panel.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(r.u,up,r.n));parent.add(panel);const w=r.b-r.a,h=r.hi-r.lo;
 const ring=(inset,band,depth)=>{if(w-2*inset<=band*2||h-2*inset<=band*2)return;const o=new T.Mesh(ringGeometry(w-2*inset,h-2*inset,band,depth,config.profile==='beaded'),material);o.name='Picture frame moulding';o.userData.railWallId=entity.id;o.castShadow=true;o.receiveShadow=true;panel.add(o);};ring(0,config.frameWidth,config.depth*.5);if(config.profile==='classic')ring(config.frameWidth*.25,config.frameWidth*.45,config.depth*.85);if(config.doubleFrame)ring(config.frameWidth+.04,.012,config.depth*.42);
 }}
